services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5180:5180"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - "5273:5273"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend
